# Generated by Django 3.1.5 on 2021-01-12 16:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tracking.models.counter, max_length=100)),
                ('category', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], max_length=100, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(default=datetime.datetime(2021, 1, 27, 16, 1, 14, 849557))),
                ('online', models.BooleanField(default=True)),
                ('complete', models.BooleanField(default=True)),
                ('for_release', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('process', models.BooleanField(default=False)),
                ('multiple_route', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(upload_to=tracking.models.pdf_file_name)),
                ('send_file', models.FileField(upload_to=tracking.models.approved_file_name)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(max_length=300, null=True)),
                ('action_taken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.actiontaken')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('date_rcv', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=100)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.actiontaken')),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.document')),
                ('routed_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.types'),
        ),
    ]
