# Generated by Django 3.1.5 on 2021-01-12 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_sent',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 27, 16, 24, 17, 576467)),
        ),
    ]
