# Generated by Django 3.1.5 on 2021-01-13 12:38

import datetime
from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210112_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='routed',
            name='attach_file',
            field=models.FileField(default=0, upload_to=tracking.models.attach_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 28, 12, 38, 29, 294165)),
        ),
    ]
