# Generated by Django 3.1.5 on 2021-01-14 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20210113_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='routed',
            name='doc_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 29, 13, 27, 45, 866373)),
        ),
    ]
