# Generated by Django 3.1.5 on 2021-01-15 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20210114_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 10, 26, 56, 151476)),
        ),
        migrations.AlterField(
            model_name='routed',
            name='doc_code',
            field=models.BigIntegerField(),
        ),
    ]
