# Generated by Django 3.1.5 on 2021-01-15 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20210115_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 11, 10, 6, 583093)),
        ),
        migrations.AlterField(
            model_name='routed',
            name='date_sent',
            field=models.DateTimeField(),
        ),
    ]
