# Generated by Django 3.1.5 on 2021-01-15 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20210115_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routed',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='routed',
            name='doc',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 16, 9, 15, 954343)),
        ),
    ]
