# Generated by Django 3.1.5 on 2021-01-19 08:23

import datetime
from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20210115_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qrcode_file',
            field=models.FileField(default=10, upload_to=tracking.models.qrcode_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 2, 3, 8, 23, 33, 296243)),
        ),
    ]
