# Generated by Django 3.1.5 on 2021-02-08 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20210127_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='qrcode_file',
        ),
        migrations.AlterField(
            model_name='document',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 2, 23, 10, 35, 51, 645231)),
        ),
    ]
