# Generated by Django 3.1.5 on 2021-02-22 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20210222_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 13, 15, 22, 32, 680545)),
        ),
    ]
