# Generated by Django 3.1.5 on 2021-02-23 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20210222_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='acted_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 14, 9, 31, 0, 907044)),
        ),
    ]
