# Generated by Django 3.1.5 on 2021-02-23 14:45

import datetime
from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20210223_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 14, 14, 45, 53, 305379)),
        ),
        migrations.AlterField(
            model_name='routed',
            name='attach_file',
            field=models.FileField(max_length=400, upload_to=tracking.models.attach_file_name),
        ),
    ]
