# Generated by Django 3.1.5 on 2021-02-24 08:35

import datetime
from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20210223_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='division',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 8, 35, 24, 350695)),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(max_length=400, upload_to=tracking.models.pdf_file_name),
        ),
        migrations.AlterField(
            model_name='document',
            name='send_file',
            field=models.FileField(max_length=400, upload_to=tracking.models.approved_file_name),
        ),
    ]
