# Generated by Django 3.1.5 on 2021-02-24 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20210224_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='division',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 8, 48, 12, 281542)),
        ),
    ]
