# Generated by Django 3.1.5 on 2021-02-24 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20210224_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='division',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 2, 46, 210101)),
        ),
    ]
