# Generated by Django 3.1.5 on 2021-02-26 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_auto_20210224_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='my_copy',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 13, 15, 57, 728365)),
        ),
    ]
