# Generated by Django 3.1.5 on 2021-03-09 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20210226_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('date_upload', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(max_length=300)),
                ('doc_to', models.CharField(max_length=300)),
                ('doc_from', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 9, 10, 28, 225215)),
        ),
    ]
