# Generated by Django 3.1.5 on 2021-03-09 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20210309_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='description',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 9, 40, 16, 154094)),
        ),
    ]
