# Generated by Django 3.1.5 on 2021-04-26 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20210309_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='attach_file',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 10, 18, 39, 60948)),
        ),
    ]
