# Generated by Django 3.1.5 on 2021-07-13 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_auto_20210712_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carboncopy',
            old_name='routed_to_id',
            new_name='routed_to',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 8, 6, 14, 8, 34, 581721)),
        ),
    ]
