# Generated by Django 3.1.5 on 2021-08-05 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0028_auto_20210713_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 9, 18, 22, 157657)),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
