# Generated by Django 3.1.5 on 2021-10-12 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0029_auto_20210805_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 11, 5, 7, 42, 49, 39798)),
        ),
        migrations.AlterField(
            model_name='routed',
            name='doc_code',
            field=models.CharField(max_length=250),
        ),
    ]
