# Generated by Django 3.1.5 on 2021-12-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0032_auto_20211215_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 12, 32, 5, 86895)),
        ),
    ]
