# Generated by Django 3.1.5 on 2021-12-15 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0033_auto_20211215_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routed',
            old_name='route',
            new_name='routed_to',
        ),
        migrations.AlterField(
            model_name='document',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 1, 8, 13, 43, 7, 516564)),
        ),
    ]
